import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import test from "node:test";

test("profile automation requires two management capabilities, preserves publication isolation, supports stop and rollback", () => {
  const child = spawnSync(process.execPath, ["--conditions=react-server", "--import", "tsx", "--input-type=module", "-e", `
    import assert from 'node:assert/strict';
    const load = async path => { const m = await import(path); return m.default || m; };
    globalThis.fetch = async () => { throw new Error('Unexpected network'); };
    const store = await load('./lib/storage.ts');
    const { sampleResult } = await load('./lib/sample-data.ts');
    const { buildPublicProfileDraft, toPublicProfile } = await load('./lib/public-profile.ts');
    const { buildAutomatedFacts } = await load('./lib/profile-automation.ts');
    const scan = { id:'automation-test-scan', targetUrl:sampleResult.targetUrl, result:sampleResult, createdAt:new Date().toISOString() };
    const watch = await store.createWatch(scan, '');
    const other = await store.createWatch({...scan,id:'other-scan'}, '');
    const draft = buildPublicProfileDraft(sampleResult);
    const profile = await store.createPublicProfilePreview(draft, {sourceScanId:scan.id});
    const separate = await store.createPublicProfilePreview(draft, {sourceScanId:scan.id});
    await store.publishPublicProfile(profile.id, profile.token);
    await store.publishPublicProfile(separate.id, separate.token);
    const pages = [{url:sampleResult.targetUrl,title:'対応地域',description:'',headings:[],text:'東京都全域の相続相談に対応しています。'}];
    const measured = {...sampleResult,scanId:'run-one'};
    assert.deepEqual(await store.refreshPublicProfileFromScan(watch.token, measured, pages), []);
    assert.equal(await store.manageProfileAutomation(profile.id, profile.token, 'enable', watch.token), null, 'free plan cannot enable');
    await store.updateWatch(watch.token, {paid:true,status:'active'});
    await store.updateWatch(other.token, {paid:true,status:'active'});
    assert.equal(await store.manageProfileAutomation(profile.id, separate.token, 'enable', watch.token), null);
    assert.equal(await store.manageProfileAutomation(profile.id, profile.token, 'enable', other.token), null);
    assert.ok(await store.manageProfileAutomation(profile.id, profile.token, 'enable', watch.token));
    const original = (await store.getPublicProfile(profile.id)).facts;
    const changed = await store.refreshPublicProfileFromScan(watch.token, measured, pages);
    assert.equal(changed.length, 1);
    assert.ok(changed[0].facts.some(f => f.value === pages[0].text));
    assert.equal(changed[0].summary, profile.summary, 'company claims are not rewritten');
    assert.deepEqual((await store.getPublicProfile(separate.id)).facts, separate.facts);
    const safe = toPublicProfile(changed[0]);
    assert.ok(safe.json.includes(pages[0].text));
    assert.ok(safe.markdown.includes(pages[0].text));
    assert.equal('automation' in safe, false);
    assert.equal('token' in safe, false);
    assert.equal(buildAutomatedFacts(changed[0], [{...pages[0],url:'https://unrelated.example/'}]), null);
    assert.equal(buildAutomatedFacts(changed[0], [{...pages[0],noindex:true}]), null);
    assert.equal(buildAutomatedFacts(changed[0], [{...pages[0],text:'東京都全域の相続相談に対応して'}]), null, 'partial sentence never removes earlier facts');
    assert.equal(buildAutomatedFacts(changed[0], [{...pages[0],text:'a'.repeat(30000)}]), null, 'crawler truncation is incomplete evidence');
    assert.equal((await store.refreshPublicProfileFromScan(watch.token, measured, pages))[0].updatedAt, changed[0].updatedAt, 'retry is idempotent');
    await store.manageProfileAutomation(profile.id, profile.token, 'disable');
    assert.deepEqual(await store.refreshPublicProfileFromScan(watch.token, {...measured,scanId:'run-two'}, pages), []);
    await store.manageProfileAutomation(profile.id, profile.token, 'rollback');
    assert.deepEqual((await store.getPublicProfile(profile.id)).facts, original);
    assert.equal((await store.getPublicProfile(profile.id)).automation.enabled, false);
    await store.manageProfileAutomation(profile.id, profile.token, 'enable', watch.token);
    await store.refreshPublicProfileFromScan(watch.token, {...measured,scanId:'run-four'}, pages);
    const newPages = [{...pages[0],text:'東京都と神奈川県の相続相談に対応しています。'}];
    await store.refreshPublicProfileFromScan(watch.token, {...measured,scanId:'run-five'}, newPages);
    await store.manageProfileAutomation(profile.id, profile.token, 'rollback');
    assert.ok((await store.getPublicProfile(profile.id)).automation.managedFacts.some(f => f.value === pages[0].text));
    await store.manageProfileAutomation(profile.id, profile.token, 'enable', watch.token);
    await store.refreshPublicProfileFromScan(watch.token, {...measured,scanId:'run-six'}, newPages);
    assert.ok(!(await store.getPublicProfile(profile.id)).facts.some(f => f.value === pages[0].text), 'rollback restores managed lineage, so stale facts are replaceable');
    await store.revokePublicProfile(profile.id, profile.token);
    assert.deepEqual(await store.refreshPublicProfileFromScan(watch.token, {...measured,scanId:'run-three'}, pages), []);
    assert.equal(await store.manageProfileAutomation(profile.id, profile.token, 'enable', watch.token), null);
  `], { encoding: "utf8", timeout: 20000, env: { ...process.env, NODE_ENV: "test", SUPABASE_URL: "", SUPABASE_SERVICE_ROLE_KEY: "" } });
  assert.equal(child.status, 0, child.stderr || String(child.error));
});
