"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { ArrowIcon, BotIcon, NetworkIcon, TrendIcon } from "@/components/icons";
import type { AgentAnalyticsSummary } from "@/lib/agent-analytics-store";

const sampleSummary: AgentAnalyticsSummary = {
  since: "2026-08-03T00:00:00.000Z", crawlerVisits: 142, referralVisits: 37, conversions: 5,
  agents: [{ agent: "OAI-SearchBot", kind: "crawler", events: 64, conversions: 0 }, { agent: "PerplexityBot", kind: "crawler", events: 41, conversions: 0 }, { agent: "Googlebot", kind: "crawler", events: 37, conversions: 0 }, { agent: "ChatGPT", kind: "referral", events: 24, conversions: 4 }, { agent: "Perplexity", kind: "referral", events: 9, conversions: 1 }, { agent: "Gemini", kind: "referral", events: 4, conversions: 0 }],
  pages: [{ path: "/pricing", crawlerVisits: 23, referralVisits: 9, conversions: 2 }, { path: "/security", crawlerVisits: 31, referralVisits: 4, conversions: 0 }, { path: "/case/enterprise", crawlerVisits: 28, referralVisits: 8, conversions: 2 }, { path: "/", crawlerVisits: 21, referralVisits: 11, conversions: 1 }],
};

export function AgentAnalyticsClient() {
  const params = useSearchParams(); const sample = params.get("sample") === "1"; const token = params.get("token") || "";
  const [summary, setSummary] = useState<AgentAnalyticsSummary | null>(sample ? sampleSummary : null); const [loading, setLoading] = useState(!sample); const [error, setError] = useState(""); const [key, setKey] = useState(sample ? "aix_ingest_SAMPLE_ONLY" : ""); const [busy, setBusy] = useState(false);
  useEffect(() => { if (sample) return; if (!token) { setError("Workspace tokenがありません。"); setLoading(false); return; } fetch(`/api/agent-analytics?token=${encodeURIComponent(token)}&days=30`, { cache: "no-store" }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error || "Agent Analyticsを取得できませんでした。"); setSummary(data); }).catch((caught) => setError(caught instanceof Error ? caught.message : "取得できませんでした。" )).finally(() => setLoading(false)); }, [sample, token]);
  async function rotate() { if (sample) { setKey("aix_ingest_SAMPLE_ROTATED_KEY"); return; } setBusy(true); setError(""); try { const response = await fetch("/api/agent-analytics/key", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ token }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Keyを発行できませんでした。"); setKey(data.ingestKey); } catch (caught) { setError(caught instanceof Error ? caught.message : "Keyを発行できませんでした。" ); } finally { setBusy(false); } }
  const back = sample ? "/workspace?sample=1" : `/workspace?token=${encodeURIComponent(token)}`;
  return <main className="agent-page"><header><Link href={back}>← AIX Workspace</Link><span>REAL EVENT LAYER</span></header><section className="agent-hero"><div><p>AGENT ANALYTICS</p><h1>AIが「読んだ」と、<br />AIから「来た」を分けて測る。</h1><span>公開クロールから訪問数を推測しません。サーバー/CDN/分析基盤から送られた実イベントだけを集計します。</span></div><NetworkIcon /></section>{loading ? <div className="agent-loading">実イベントを読み込んでいます。</div> : null}{summary ? <><section className="agent-kpis"><article><BotIcon /><small>AI crawler visits</small><strong>{summary.crawlerVisits}</strong><span>過去30日</span></article><article><ArrowIcon /><small>AI referral visits</small><strong>{summary.referralVisits}</strong><span>ChatGPT / Perplexity / Gemini等</span></article><article><TrendIcon /><small>Marked conversions</small><strong>{summary.conversions}</strong><span>送信側でconversion=trueのイベント</span></article></section><section className="agent-grid"><article><header><strong>Agents / Referrers</strong><span>実イベント数</span></header>{summary.agents.map((item) => <div className="agent-row" key={`${item.kind}-${item.agent}`}><span className={item.kind}>{item.kind}</span><strong>{item.agent}</strong><i><b style={{ width: `${Math.min(100, item.events / Math.max(1, summary.crawlerVisits + summary.referralVisits) * 180)}%` }} /></i><em>{item.events}</em><small>{item.conversions ? `${item.conversions} conv.` : ""}</small></div>)}</article><article><header><strong>Top pages</strong><span>crawler / referral / conversion</span></header>{summary.pages.map((page) => <div className="agent-page-row" key={page.path}><strong>{page.path}</strong><span>{page.crawlerVisits}</span><span>{page.referralVisits}</span><span>{page.conversions}</span></div>)}</article></section></> : null}<section className="agent-setup"><div><p>CONNECT REAL LOGS</p><h2>Ingest keyを1つ発行する。</h2><span>キーは再発行可能です。AIXはRaw IPを受け取る必要がありません。User-Agent、path、referrer、status、任意のconversionフラグだけ送ります。</span></div><article><button onClick={rotate} disabled={busy}>{busy ? "発行中…" : key ? "Ingest keyを再発行" : "Ingest keyを発行"}</button>{key ? <><small>今回だけ表示</small><code>{key}</code><pre>{`POST /api/agent-analytics/ingest\nX-AIX-Ingest-Key: ${key}\n\n{\n  "events": [{\n    "occurredAt": "2026-09-02T00:00:00Z",\n    "userAgent": "OAI-SearchBot/1.0",\n    "path": "/pricing",\n    "referrer": "",\n    "statusCode": 200,\n    "conversion": false\n  }]\n}`}</pre></> : <p>接続するまでAgent Analyticsは0件のままです。AIXが訪問数を推測して埋めることはありません。</p>}</article></section>{error ? <div className="agent-error">{error}</div> : null}</main>;
}
