"use client";

import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { BuyerDecisionMap } from "@/components/visuals";
import { Icon, Pill } from "@/components/ui";
import type { Observation, ScanResult } from "@/lib/types";

function providerLabel(value: Observation["provider"]) { return value === "openai" ? "OpenAI" : value === "gemini" ? "Gemini" : "Perplexity"; }
function date(value:string){return new Intl.DateTimeFormat("ja-JP",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Tokyo"}).format(new Date(value))}

export function ReportView({ result, demo = false }: { result: ScanResult; demo?: boolean }) {
  const router=useRouter(); const [open,setOpen]=useState<string | null>(null); const [email,setEmail]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const winner=result.metrics.competitors[0]?.name||result.lostPrompts[0]?.winner||"競合候補";
  const primary=result.lostPrompts[0];
  const providerStats=useMemo(()=>["openai","gemini","perplexity"].map(provider=>{const rows=result.observations.filter(item=>item.provider===provider);return {provider,success:rows.filter(item=>item.status==="success").length,total:rows.length,own:rows.filter(item=>item.ownRecommended).length}}),[result]);

  async function startWatch(event:FormEvent){event.preventDefault();if(demo){router.push("/watch/demo?token=demo-token");return}setBusy(true);setError("");try{const response=await fetch("/api/watch",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({scanId:result.scanId,email})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Watchを開始できませんでした。");router.push(`/watch/${encodeURIComponent(data.id)}?token=${encodeURIComponent(data.token)}`)}catch(caught){setError(caught instanceof Error?caught.message:"Watchを開始できませんでした。")}finally{setBusy(false)}}

  return <main className="report-page">
    <header className="report-topbar"><div className="container"><Link className="logo" href="/"><span className="logo-mark"><i/><i/><i/></span><span>AIX</span><small>Recommendation Signal</small></Link><nav><Link href="/methodology">測定方法</Link><Link href="/pricing">料金</Link><Link href="/">別の会社を調べる</Link></nav></div></header>
    <section className="report-hero"><div className="container"><div className="report-hero-row"><div><p className="kicker light"><span/>{demo?"FICTIONAL DEMO":"AI MARKET SNAPSHOT"}</p><h1>{result.discovery.brandName}は、<br/>AI比較で<em>{result.metrics.marketPosition}/{result.metrics.marketSize}位</em>です。</h1><p>{result.prompts.length}のBuyer Promptを主要AIへ投げ、{result.metrics.ownRecommendationCount}/{result.metrics.successfulObservations}回答で購入候補に入りました。{result.metrics.lostPromptCount}テーマでは候補外です。</p></div><span className="confidence">市場認識 {Math.round(result.discovery.confidence*100)}%</span></div><div className="report-meta"><span>OpenAI / Gemini / Perplexity</span><span>{result.prompts.length} Buyer Prompts</span><span>{result.metrics.successfulObservations}/{result.metrics.scheduledObservations} successful</span><span>{date(result.measuredAt)}</span><span>日本語・日本市場</span></div><div className="warning-stack">{result.warnings.map(warning=><p key={warning}>{warning}</p>)}</div></div></section>

    <section className="report-section"><div className="container"><div className="section-head"><div><p className="kicker"><span/>EXECUTIVE VIEW</p><h2>AIが競合を選び、<br/>御社を外した構造。</h2></div><p>最初に細かいスコアではなく、買い手の質問から推薦候補が決まる流れを見せます。</p></div><BuyerDecisionMap winner={winner} own={result.discovery.brandName} lostCount={result.metrics.lostPromptCount}/></div></section>

    <section className="report-section alt"><div className="container"><div className="section-head"><div><p className="kicker"><span/>MARKET POSITION</p><h2>候補入り率と競合差。</h2></div><p>名前が出ただけではなく、購入候補として列挙された成功回答を分母にしています。</p></div><div className="metric-grid"><article><span>市場での位置</span><strong>{result.metrics.marketPosition}/{result.metrics.marketSize}</strong><small>{result.discovery.market}</small></article><article className="metric-bad"><span>Shortlist Coverage</span><strong>{result.metrics.shortlistCoverage}%</strong><small>{result.metrics.ownRecommendationCount}/{result.metrics.successfulObservations}回答</small></article><article className="metric-accent"><span>Top Choice Rate</span><strong>{result.metrics.topChoiceRate}%</strong><small>最初の推薦候補</small></article><article><span>測定安定性</span><strong>{result.metrics.stability}%</strong><small>反復結果の一致度</small></article></div><div className="comparison-panel"><div className="comparison-head"><h3>同じ質問群での候補入り率</h3><span>{result.metrics.successfulObservations} observations</span></div>{result.metrics.competitors.slice(0,7).map(item=><div className="comparison-row" key={item.name}><span>{item.name}</span><i><b style={{width:`${item.coverage}%`}}/></i><strong>{item.coverage}%</strong></div>)}<div className="comparison-row self"><span>{result.discovery.brandName}</span><i><b style={{width:`${result.metrics.shortlistCoverage}%`}}/></i><strong>{result.metrics.shortlistCoverage}%</strong></div></div><div className="provider-status">{providerStats.map(item=><article key={item.provider}><span>{providerLabel(item.provider as Observation["provider"])}</span><strong>{item.own}/{item.success}</strong><small>候補入り / 成功回答</small></article>)}</div></div></section>

    <section className="report-section"><div className="container"><div className="section-head"><div><p className="kicker"><span/>BIGGEST LOST INTENT</p><h2>最も大きい取りこぼし。</h2></div><p>生回答とCitationを開き、AIXの解釈が正しいか自分で監査できます。</p></div>{primary?<><div className="lost-layout"><article className="lost-panel"><small>PURCHASE-READY QUESTION</small><h3>「{primary.prompt.text}」</h3><div className="lost-outcomes"><div><span>最頻推薦</span><strong>{primary.winner||"競合候補"}</strong></div><div><span>{result.discovery.brandName}</span><strong className="bad">候補外</strong></div></div></article><aside className="citation-list"><h3>AIが使った引用元</h3><ol>{primary.citations.slice(0,8).map((citation,index)=><li key={`${citation.url}-${index}`}><span>{String(index+1).padStart(2,"0")}</span><a href={citation.url} target="_blank" rel="noreferrer">{citation.title||citation.domain}</a></li>)}</ol></aside></div><div className="raw-list">{primary.observations.map(observation=><article className="raw-item" key={observation.id}><button type="button" onClick={()=>setOpen(open===observation.id?null:observation.id)} aria-expanded={open===observation.id}><strong>{providerLabel(observation.provider)}</strong><span>Run {observation.repetition}</span><span>{observation.ownPosition?`自社 ${observation.ownPosition}番目`:"自社候補外"}</span><i>⌄</i></button>{open===observation.id?<pre>{observation.rawText}</pre>:null}</article>)}</div></>:<div className="decision-map"><h3>今回の主要質問では候補外を確認できませんでした。</h3><p>Watchで新しい質問表現と競合を追跡します。</p></div>}</div></section>

    <section className="report-section alt"><div className="container"><div className="section-head"><div><p className="kicker"><span/>EVIDENCE GAPS</p><h2>AIが比較に使えない、<br/>未確認の証拠。</h2></div><p>「存在しない」と断定せず、公開Webから確認できなかった事実だけを示します。</p></div><div className="evidence-grid">{result.evidenceGaps.slice(0,6).map(gap=><article key={gap.id}><header><span>関連Prompt</span><strong>{gap.relatedPromptCount}件</strong></header><h3>{gap.label}</h3><p>{gap.whyItMatters}</p><small>{gap.competitorEvidence}</small><small>Confidence {Math.round(gap.confidence*100)}%</small></article>)}</div></div></section>

    <section className="report-section"><div className="container"><div className="section-head"><div><p className="kicker"><span/>ACTION QUEUE</p><h2>次に直すことを、<br/>優先順位まで決める。</h2></div><p>期待効果を捏造せず、Buyer Intent、負けた頻度、競合差、診断確度から並べます。</p></div><div className="action-list">{result.actions.map(action=><article className="action-card" key={action.id}><span className={`priority-${action.priority}`}>{action.priority}</span><div><h3>{action.title}</h3><p>{action.rationale}</p></div><aside><span>{action.relatedPromptCount} prompts</span><span>{action.target}</span></aside></article>)}</div></div></section>

    <section className="watch-cta"><div className="container watch-cta-grid"><div><p className="kicker light"><span/>14-DAY WATCH</p><h2>この市場を、14日間無料で追跡する。</h2><p>同じCore Promptを再測定し、候補入り、競合、Citation、Evidenceの変化を確認します。カードは不要です。</p></div><form className="watch-form" onSubmit={startWatch}><label>会社メール<input type="email" required value={email} onChange={event=>setEmail(event.target.value)} placeholder="you@company.jp"/></label><button className="button button-primary" disabled={busy}>{busy?"Watchを準備中…":"無料Watchを開始"} <Icon name="arrow" size={17}/></button><small>無料期間から自動課金へ移行しません。</small>{error?<p className="form-error">{error}</p>:null}</form></div></section>
  </main>;
}
