"use client";

import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";
import { WatchTrendVisual } from "@/components/visuals";
import { Icon } from "@/components/ui";
import type { WatchRecord } from "@/lib/types";

export function WatchView({ initial, token, demo = false }: { initial: WatchRecord; token: string; demo?: boolean }) {
  const [watch,setWatch]=useState(initial); const [values,setValues]=useState<Record<string,string>>({}); const [message,setMessage]=useState(""); const [busy,setBusy]=useState("");
  const delta=useMemo(()=>({coverage:watch.latest.metrics.shortlistCoverage-watch.baseline.metrics.shortlistCoverage,rank:watch.baseline.metrics.marketPosition-watch.latest.metrics.marketPosition,wins:watch.latest.metrics.ownRecommendationCount-watch.baseline.metrics.ownRecommendationCount}),[watch]);
  async function evidence(event:FormEvent,gapId:string){event.preventDefault();if(demo){setMessage("デモでは保存しません。実際のWatchでは非公開Evidenceとして保存されます。");return}const value=values[gapId]?.trim();if(!value)return;setBusy(gapId);try{const response=await fetch(`/api/watch/${watch.id}/evidence`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,gapId,value})});const data=await response.json();if(!response.ok)throw new Error(data.error||"保存できませんでした。");setWatch(data.watch);setMessage("Evidenceを非公開で保存しました。") }catch(caught){setMessage(caught instanceof Error?caught.message:"保存できませんでした。")}finally{setBusy("")}}
  async function checkout(){if(demo){setMessage("デモでは決済を開始しません。");return}setBusy("checkout");try{const response=await fetch("/api/billing/checkout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({watchId:watch.id,token})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Checkoutを開始できませんでした。");window.location.assign(data.url)}catch(caught){setMessage(caught instanceof Error?caught.message:"Checkoutを開始できませんでした。")}finally{setBusy("")}}
  return <main className="watch-page">
    <header className="report-topbar"><div className="container"><Link className="logo" href="/"><span className="logo-mark"><i/><i/><i/></span><span>AIX</span><small>Recommendation Signal</small></Link><nav><Link href={demo?"/demo":`/report/${watch.scanId}`}>診断結果</Link><Link href="/methodology">測定方法</Link><Link href="/pricing">料金</Link></nav></div></header>
    <section className="watch-hero"><div className="container"><p className="kicker light"><span/>AIX WATCH · {demo?"FICTIONAL DEMO":watch.status.toUpperCase()}</p><h1>AI上の市場を、<br/>同じ条件で追い続ける。</h1><p>{watch.latest.discovery.brandName} / {watch.latest.discovery.market} · 次回測定 {new Date(watch.nextRunAt).toLocaleString("ja-JP")}</p>{demo?<div className="warning-stack"><p>会社・競合・数値はすべて架空のWatchデモです。</p></div>:null}</div></section>
    <section className="watch-summary"><div className="container watch-summary-grid"><WatchTrendVisual/><div className="watch-kpis"><article><span>Shortlist Coverage</span><strong>{watch.baseline.metrics.shortlistCoverage}% → {watch.latest.metrics.shortlistCoverage}%</strong><small>{delta.coverage>=0?"+":""}{delta.coverage}pt · 観測変化</small></article><article><span>市場順位</span><strong>{watch.baseline.metrics.marketPosition}位 → {watch.latest.metrics.marketPosition}位</strong><small>{delta.rank>=0?"+":""}{delta.rank}順位</small></article><article><span>新しく候補入り</span><strong>+{Math.max(0,delta.wins)}</strong><small>AI回答</small></article><article><span>測定安定性</span><strong>{watch.latest.metrics.stability}%</strong><small>反復一致率</small></article></div></div></section>
    <section className="report-section alt" id="need-you"><div className="container"><div className="section-head"><div><p className="kicker"><span/>NEED YOU</p><h2>次の判断に必要な、<br/>企業しか持っていない事実。</h2></div><p>入力する理由と関連するBuyer Promptを先に示します。公開はされません。</p></div><div className="watch-needs">{watch.latest.evidenceGaps.slice(0,4).map(gap=>{const saved=watch.evidence.find(item=>item.gapId===gap.id);return <article key={gap.id}><header><strong>{gap.label}</strong><span>{gap.relatedPromptCount} prompts</span></header><p>{saved?`入力済み: ${saved.value}`:gap.whyItMatters}</p>{!saved?<form onSubmit={event=>evidence(event,gap.id)}><input value={values[gap.id]||""} onChange={event=>setValues(current=>({...current,[gap.id]:event.target.value}))} placeholder="分かる範囲で入力"/><button disabled={busy===gap.id}>{busy===gap.id?"保存中":"非公開で保存"}</button></form>:<span className="confidence">company_asserted</span>}</article>})}</div>{message?<p className="warning-stack"><span>{message}</span></p>:null}</div></section>
    <section className="report-section"><div className="container"><div className="section-head"><div><p className="kicker"><span/>THIS WEEK</p><h2>AIXが見つけた、<br/>次の優先Action。</h2></div><p>数値の変化を施策の因果とは断定せず、Evidence差と候補外Promptから優先します。</p></div><div className="action-list">{watch.latest.actions.slice(0,4).map(action=><article className="action-card" key={action.id}><span className={`priority-${action.priority}`}>{action.priority}</span><div><h3>{action.title}</h3><p>{action.rationale}</p></div><aside><span>{action.relatedPromptCount} prompts</span><span>{action.target}</span></aside></article>)}</div></div></section>
    <section className="watch-price"><div className="container watch-price-grid"><div><p className="kicker"><span/>CONTINUE THE SIGNAL</p><h2>監視を止めず、<br/>改善判断を更新する。</h2><p>固定Core Prompt 50件を3 AIへ各3回、週次で再測定。全回答・Citation・Evidence・Action履歴を保持します。</p></div><article className="watch-price-card"><span>FOUNDER WATCH</span><strong>¥29,800</strong><small>月額・税別・1ブランド</small><ul><li>50 Core Prompts</li><li>3 AI × 各3回 × 週次</li><li>Evidence Inbox</li><li>全生回答・Citation・履歴</li><li>いつでも次回更新を停止</li></ul><button className="button button-primary" type="button" onClick={checkout} disabled={busy==="checkout"||watch.paid}>{watch.paid?"契約中":busy==="checkout"?"準備中…":"AIX Watchを継続"} <Icon name="arrow" size={17}/></button></article></div></section>
  </main>;
}
