export const WATCH_MONTHLY_PRICE_TAX_INCLUSIVE = 19_800;
export const WATCH_MONTHLY_PRICE_TAX_EXCLUSIVE = 18_000;
export const WATCH_MONTHLY_PRICE_LABEL = "月額19,800円（税込）";
export const WATCH_MONTHLY_PRICE_TAX_EXCLUSIVE_LABEL = "税別18,000円";
