export const WATCH_MONTHLY_PRICE_TAX_INCLUSIVE = 10_780;
export const WATCH_MONTHLY_PRICE_TAX_EXCLUSIVE = 9_800;
export const WATCH_MONTHLY_PRICE_LABEL = "月額10,780円（税込）";
export const WATCH_MONTHLY_PRICE_TAX_EXCLUSIVE_LABEL = "税別9,800円";
